name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04, windows-latest]
        include:
          - os: macos-13
            imgui-dir: lua-imgui-macos
          - os: ubuntu-22.04
            imgui-dir: lua-imgui-ubuntu
          - os: windows-latest
            imgui-dir: lua-imgui-windows
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install libgl
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install libgl-dev libxext-dev
          
      - name: Build and install Lua ImGui modules
        shell: bash
        run: |
          export MACOSX_DEPLOYMENT_TARGET='13.0'
          export BUILD_DIR=$(pwd)/${{ matrix.imgui-dir }}
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=11 -DLUAJIT_BIN=${BUILD_DIR}
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            bash -c "sed 's/abs(a.x/fabs(a.x/g' -i build/_deps/luajit-imgui-src/cimnodes_r/ImNodes/ImNodes.cpp"
            bash -c "sed 's/abs(a.y/fabs(a.y/g' -i build/_deps/luajit-imgui-src/cimnodes_r/ImNodes/ImNodes.cpp"
          fi
          cmake --build build --config Release --parallel 16 --verbose
          cmake --build build --config Release -t install
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.imgui-dir }}
          path: ${{ github.workspace }}/${{ matrix.imgui-dir }}/
          
